const profileActionTypes = {
    SEARCH_PROFILE: 'SEARCH_PROFILE',
    GET_PROFILE_START: 'GET_PROFILE_START',
    GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
    GET_PROFILES_FAILURE: 'GET_PROFILES_FAILURE',
};

export default profileActionTypes;