const articleActionTypes = {
    GET_ARTICLES_FROM_LS: 'GET_ARTICLES_FROM_LS',

    GET_ARTICLES_START: 'GET_ARTICLES_START',
    GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
    GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',

    CREATE_ARTICLE_START: 'CREATE_ARTICLE_START',
    CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_FAILURE: 'CREATE_ARTICLE_FAILURE',
    
    DELETE_ARTICLE_START: 'DELETE_ARTICLE_START',
    DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
    DELETE_ARTICLE_FAILURE: 'DELETE_ARTICLE_FAILURE',
    
    DELETE_ARTICLE: 'DELETE_ARTICLE'
}

export default articleActionTypes;