const userActionTypes = {
    GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
    // GET_PROFILE_START: 'GET_PROFILE_START',
    // GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
    // GET_PROFILES_FAILURE: 'GET_PROFILES_FAILURE',
};

export default userActionTypes;